# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 02:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20160402_0246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='is_active',
            new_name='published',
        ),
    ]
