# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 03:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20160402_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2016, 4, 2, 3, 3, 2, 428399, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='date_published',
            field=models.DateField(blank=True, null=True),
        ),
    ]
