# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_auto_20160402_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_published',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
