# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_blog_date_unpublished'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='sub_title',
            new_name='author',
        ),
    ]
